#!/bin/bash

# Define the filename and size
FILENAME="largefile.bin"
SIZE="2G"

# Create the file filled with random data
dd if=/dev/urandom of=$FILENAME bs=$SIZE count=1
echo "Created $FILENAME with $SIZE of data."
